repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
    -   id: mypy
        files: ^deadseeker/  
        args: [--disallow-untyped-defs]
        additional_dependencies: [aiohttp-retry==2.8.3] # we need to install this dependency for mypy's venv to find the types
