repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    -   id: mypy
        args: [deadseeker, --disallow-untyped-defs]