name: 'Broken-Links-Crawler'
description: 'Checks a webiste for broken links'
branding:
  color: red
  icon: check-circle
inputs:
  website_url:  # id of input
    description: 'Which website to check'
    required: true
  verbose:
    description: 'Turn verbose mode on/off'
    require: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
    # don't put args here, python will read them from env
