# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # installing dependencies used by this action
        pip install flake8 pytest
        # installing dependencies used by the project
        if [ -f test-requirements.txt ]; then \
          pip install -r test-requirements.txt; \
        elif [ -f requirements.txt ]; then \
           pip install -r requirements.txt; \
        fi
    - name: Lint with flake8
      run: |
        # stop the build if there are any formating or code quality failures
        flake8 . --count --show-source --max-complexity=10 --statistics
    - name: Test with pytest
      run: |
        pytest --cov=deadseeker --cov-fail-under=95 --cov-branch --cov-report=term-missing
    - name: Set ci docker label
      run: echo "CI_DOCKER_LABEL=broken-links-crawler-action:ci-$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.CI_DOCKER_LABEL }}
    - name: Test the Docker image
      run: |
        docker run \
          -e INPUT_WEBSITE_URL="https://github.com/ScholliYT/Broken-Links-Crawler-Action" \
          -e INPUT_VERBOSE="true" \
          -e INPUT_MAX_RETRY_TIME=30 \
          -e INPUT_MAX_RETRIES=5 \
          -e INPUT_MAX_DEPTH=0 \
          -e INPUT_EXCLUDE_URL_PREFIX="mailto:,https://www.linkedin.com,https://linkedin.com" \
          ${{ env.CI_DOCKER_LABEL }}